
spring.application.name=recipefinder
server.port=8080

spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:OftfzdgJtcHhAbwAztfujeIcmlUnQugg}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spoonacular.api.key=${SPOONACULAR_API_KEY:9004a77a1623435980e31a7a6590c3f2}

spoonacular.api.base-url=https://api.spoonacular.com
 