# spring.application.name=recipefinder
# spoonacular.api.key=${}
# spoonacular.api.base-url=https://api.spoonacular.com
# spring.datasource.url=
# spring.datasource.username=
# spring.datasource.password=
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# server.port=8080

spoonacular.api.key=${9004a77a1623435980e31a7a6590c3f2}

spring.datasource.url=${jdbc:mysql://mysql.railway.internal:3306/railway}

spring.datasource.username=${root}

spring.datasource.password=${OftfzdgJtcHhAbwAztfujeIcmlUnQugg}